// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inference.proto
// Protobuf Java Version: 4.31.0

package io.pyserve.inference.v1;

@com.google.protobuf.Generated
public final class Inference {
  private Inference() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      Inference.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_pyserve_inference_v1_PredictionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_pyserve_inference_v1_PredictionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_pyserve_inference_v1_PredictionRequest_InputsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_pyserve_inference_v1_PredictionRequest_InputsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_pyserve_inference_v1_PredictionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_pyserve_inference_v1_PredictionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_pyserve_inference_v1_PredictionResponse_OutputsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_pyserve_inference_v1_PredictionResponse_OutputsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017inference.proto\022\027io.pyserve.inference." +
      "v1\032\014tensor.proto\032\027google/rpc/status.prot" +
      "o\"\340\001\n\021PredictionRequest\022\022\n\nmodel_name\030\001 " +
      "\001(\t\022\025\n\rmodel_version\030\002 \001(\t\022F\n\006inputs\030\003 \003" +
      "(\01326.io.pyserve.inference.v1.PredictionR" +
      "equest.InputsEntry\032X\n\013InputsEntry\022\013\n\003key" +
      "\030\001 \001(\t\0228\n\005value\030\002 \001(\0132).io.pyserve.infer" +
      "ence.v1.TorchTensorProto:\0028\001\"\356\001\n\022Predict" +
      "ionResponse\022I\n\007outputs\030\001 \003(\01328.io.pyserv" +
      "e.inference.v1.PredictionResponse.Output" +
      "sEntry\022\'\n\006status\030\002 \001(\0132\022.google.rpc.Stat" +
      "usH\000\210\001\001\032Y\n\014OutputsEntry\022\013\n\003key\030\001 \001(\t\0228\n\005" +
      "value\030\002 \001(\0132).io.pyserve.inference.v1.To" +
      "rchTensorProto:\0028\001B\t\n\007_status2x\n\020Inferen" +
      "ceService\022d\n\007Predict\022*.io.pyserve.infere" +
      "nce.v1.PredictionRequest\032+.io.pyserve.in" +
      "ference.v1.PredictionResponse\"\000B\002P\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.pyserve.inference.v1.Tensor.getDescriptor(),
          com.google.rpc.StatusProto.getDescriptor(),
        });
    internal_static_io_pyserve_inference_v1_PredictionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_pyserve_inference_v1_PredictionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_pyserve_inference_v1_PredictionRequest_descriptor,
        new java.lang.String[] { "ModelName", "ModelVersion", "Inputs", });
    internal_static_io_pyserve_inference_v1_PredictionRequest_InputsEntry_descriptor =
      internal_static_io_pyserve_inference_v1_PredictionRequest_descriptor.getNestedTypes().get(0);
    internal_static_io_pyserve_inference_v1_PredictionRequest_InputsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_pyserve_inference_v1_PredictionRequest_InputsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_io_pyserve_inference_v1_PredictionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_pyserve_inference_v1_PredictionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_pyserve_inference_v1_PredictionResponse_descriptor,
        new java.lang.String[] { "Outputs", "Status", });
    internal_static_io_pyserve_inference_v1_PredictionResponse_OutputsEntry_descriptor =
      internal_static_io_pyserve_inference_v1_PredictionResponse_descriptor.getNestedTypes().get(0);
    internal_static_io_pyserve_inference_v1_PredictionResponse_OutputsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_pyserve_inference_v1_PredictionResponse_OutputsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
    io.pyserve.inference.v1.Tensor.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
