// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inference.proto
// Protobuf Java Version: 4.31.0

package io.pyserve.inference.v1;

/**
 * Protobuf type {@code io.pyserve.inference.v1.PredictionResponse}
 */
@com.google.protobuf.Generated
public final class PredictionResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.pyserve.inference.v1.PredictionResponse)
    PredictionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      PredictionResponse.class.getName());
  }
  // Use PredictionResponse.newBuilder() to construct.
  private PredictionResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PredictionResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.pyserve.inference.v1.Inference.internal_static_io_pyserve_inference_v1_PredictionResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetOutputs();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.pyserve.inference.v1.Inference.internal_static_io_pyserve_inference_v1_PredictionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.pyserve.inference.v1.PredictionResponse.class, io.pyserve.inference.v1.PredictionResponse.Builder.class);
  }

  private int bitField0_;
  public static final int OUTPUTS_FIELD_NUMBER = 1;
  private static final class OutputsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto>newDefaultInstance(
                io.pyserve.inference.v1.Inference.internal_static_io_pyserve_inference_v1_PredictionResponse_OutputsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                io.pyserve.inference.v1.Tensor.TorchTensorProto.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> outputs_;
  private com.google.protobuf.MapField<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto>
  internalGetOutputs() {
    if (outputs_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          OutputsDefaultEntryHolder.defaultEntry);
    }
    return outputs_;
  }
  public int getOutputsCount() {
    return internalGetOutputs().getMap().size();
  }
  /**
   * <pre>
   * Output tensors.
   * </pre>
   *
   * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
   */
  @java.lang.Override
  public boolean containsOutputs(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetOutputs().getMap().containsKey(key);
  }
  /**
   * Use {@link #getOutputsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> getOutputs() {
    return getOutputsMap();
  }
  /**
   * <pre>
   * Output tensors.
   * </pre>
   *
   * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> getOutputsMap() {
    return internalGetOutputs().getMap();
  }
  /**
   * <pre>
   * Output tensors.
   * </pre>
   *
   * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
io.pyserve.inference.v1.Tensor.TorchTensorProto getOutputsOrDefault(
      java.lang.String key,
      /* nullable */
io.pyserve.inference.v1.Tensor.TorchTensorProto defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> map =
        internalGetOutputs().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Output tensors.
   * </pre>
   *
   * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
   */
  @java.lang.Override
  public io.pyserve.inference.v1.Tensor.TorchTensorProto getOutputsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> map =
        internalGetOutputs().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private com.google.rpc.Status status_;
  /**
   * <pre>
   * optional
   * </pre>
   *
   * <code>optional .google.rpc.Status status = 2;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * optional
   * </pre>
   *
   * <code>optional .google.rpc.Status status = 2;</code>
   * @return The status.
   */
  @java.lang.Override
  public com.google.rpc.Status getStatus() {
    return status_ == null ? com.google.rpc.Status.getDefaultInstance() : status_;
  }
  /**
   * <pre>
   * optional
   * </pre>
   *
   * <code>optional .google.rpc.Status status = 2;</code>
   */
  @java.lang.Override
  public com.google.rpc.StatusOrBuilder getStatusOrBuilder() {
    return status_ == null ? com.google.rpc.Status.getDefaultInstance() : status_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetOutputs(),
        OutputsDefaultEntryHolder.defaultEntry,
        1);
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getStatus());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> entry
         : internalGetOutputs().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto>
      outputs__ = OutputsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, outputs__);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStatus());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.pyserve.inference.v1.PredictionResponse)) {
      return super.equals(obj);
    }
    io.pyserve.inference.v1.PredictionResponse other = (io.pyserve.inference.v1.PredictionResponse) obj;

    if (!internalGetOutputs().equals(
        other.internalGetOutputs())) return false;
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetOutputs().getMap().isEmpty()) {
      hash = (37 * hash) + OUTPUTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetOutputs().hashCode();
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.pyserve.inference.v1.PredictionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pyserve.inference.v1.PredictionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pyserve.inference.v1.PredictionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pyserve.inference.v1.PredictionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pyserve.inference.v1.PredictionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pyserve.inference.v1.PredictionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pyserve.inference.v1.PredictionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.pyserve.inference.v1.PredictionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.pyserve.inference.v1.PredictionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.pyserve.inference.v1.PredictionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.pyserve.inference.v1.PredictionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.pyserve.inference.v1.PredictionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.pyserve.inference.v1.PredictionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.pyserve.inference.v1.PredictionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.pyserve.inference.v1.PredictionResponse)
      io.pyserve.inference.v1.PredictionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.pyserve.inference.v1.Inference.internal_static_io_pyserve_inference_v1_PredictionResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetOutputs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableOutputs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.pyserve.inference.v1.Inference.internal_static_io_pyserve_inference_v1_PredictionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.pyserve.inference.v1.PredictionResponse.class, io.pyserve.inference.v1.PredictionResponse.Builder.class);
    }

    // Construct using io.pyserve.inference.v1.PredictionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetStatusFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableOutputs().clear();
      status_ = null;
      if (statusBuilder_ != null) {
        statusBuilder_.dispose();
        statusBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.pyserve.inference.v1.Inference.internal_static_io_pyserve_inference_v1_PredictionResponse_descriptor;
    }

    @java.lang.Override
    public io.pyserve.inference.v1.PredictionResponse getDefaultInstanceForType() {
      return io.pyserve.inference.v1.PredictionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.pyserve.inference.v1.PredictionResponse build() {
      io.pyserve.inference.v1.PredictionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.pyserve.inference.v1.PredictionResponse buildPartial() {
      io.pyserve.inference.v1.PredictionResponse result = new io.pyserve.inference.v1.PredictionResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.pyserve.inference.v1.PredictionResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.outputs_ = internalGetOutputs().build(OutputsDefaultEntryHolder.defaultEntry);
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.status_ = statusBuilder_ == null
            ? status_
            : statusBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.pyserve.inference.v1.PredictionResponse) {
        return mergeFrom((io.pyserve.inference.v1.PredictionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.pyserve.inference.v1.PredictionResponse other) {
      if (other == io.pyserve.inference.v1.PredictionResponse.getDefaultInstance()) return this;
      internalGetMutableOutputs().mergeFrom(
          other.internalGetOutputs());
      bitField0_ |= 0x00000001;
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto>
              outputs__ = input.readMessage(
                  OutputsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableOutputs().ensureBuilderMap().put(
                  outputs__.getKey(), outputs__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetStatusFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private static final class OutputsConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder, io.pyserve.inference.v1.Tensor.TorchTensorProto> {
      @java.lang.Override
      public io.pyserve.inference.v1.Tensor.TorchTensorProto build(io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder val) {
        if (val instanceof io.pyserve.inference.v1.Tensor.TorchTensorProto) { return (io.pyserve.inference.v1.Tensor.TorchTensorProto) val; }
        return ((io.pyserve.inference.v1.Tensor.TorchTensorProto.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> defaultEntry() {
        return OutputsDefaultEntryHolder.defaultEntry;
      }
    };
    private static final OutputsConverter outputsConverter = new OutputsConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder, io.pyserve.inference.v1.Tensor.TorchTensorProto, io.pyserve.inference.v1.Tensor.TorchTensorProto.Builder> outputs_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder, io.pyserve.inference.v1.Tensor.TorchTensorProto, io.pyserve.inference.v1.Tensor.TorchTensorProto.Builder>
        internalGetOutputs() {
      if (outputs_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(outputsConverter);
      }
      return outputs_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder, io.pyserve.inference.v1.Tensor.TorchTensorProto, io.pyserve.inference.v1.Tensor.TorchTensorProto.Builder>
        internalGetMutableOutputs() {
      if (outputs_ == null) {
        outputs_ = new com.google.protobuf.MapFieldBuilder<>(outputsConverter);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return outputs_;
    }
    public int getOutputsCount() {
      return internalGetOutputs().ensureBuilderMap().size();
    }
    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
     */
    @java.lang.Override
    public boolean containsOutputs(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetOutputs().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getOutputsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> getOutputs() {
      return getOutputsMap();
    }
    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> getOutputsMap() {
      return internalGetOutputs().getImmutableMap();
    }
    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
io.pyserve.inference.v1.Tensor.TorchTensorProto getOutputsOrDefault(
        java.lang.String key,
        /* nullable */
io.pyserve.inference.v1.Tensor.TorchTensorProto defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder> map = internalGetMutableOutputs().ensureBuilderMap();
      return map.containsKey(key) ? outputsConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
     */
    @java.lang.Override
    public io.pyserve.inference.v1.Tensor.TorchTensorProto getOutputsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder> map = internalGetMutableOutputs().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return outputsConverter.build(map.get(key));
    }
    public Builder clearOutputs() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableOutputs().clear();
      return this;
    }
    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
     */
    public Builder removeOutputs(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableOutputs().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto>
        getMutableOutputs() {
      bitField0_ |= 0x00000001;
      return internalGetMutableOutputs().ensureMessageMap();
    }
    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
     */
    public Builder putOutputs(
        java.lang.String key,
        io.pyserve.inference.v1.Tensor.TorchTensorProto value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableOutputs().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
     */
    public Builder putAllOutputs(
        java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> values) {
      for (java.util.Map.Entry<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableOutputs().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * Output tensors.
     * </pre>
     *
     * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
     */
    public io.pyserve.inference.v1.Tensor.TorchTensorProto.Builder putOutputsBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder> builderMap = internalGetMutableOutputs().ensureBuilderMap();
      io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = io.pyserve.inference.v1.Tensor.TorchTensorProto.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof io.pyserve.inference.v1.Tensor.TorchTensorProto) {
        entry = ((io.pyserve.inference.v1.Tensor.TorchTensorProto) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (io.pyserve.inference.v1.Tensor.TorchTensorProto.Builder) entry;
    }

    private com.google.rpc.Status status_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder> statusBuilder_;
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>optional .google.rpc.Status status = 2;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>optional .google.rpc.Status status = 2;</code>
     * @return The status.
     */
    public com.google.rpc.Status getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? com.google.rpc.Status.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>optional .google.rpc.Status status = 2;</code>
     */
    public Builder setStatus(com.google.rpc.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
      } else {
        statusBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>optional .google.rpc.Status status = 2;</code>
     */
    public Builder setStatus(
        com.google.rpc.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>optional .google.rpc.Status status = 2;</code>
     */
    public Builder mergeStatus(com.google.rpc.Status value) {
      if (statusBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          status_ != null &&
          status_ != com.google.rpc.Status.getDefaultInstance()) {
          getStatusBuilder().mergeFrom(value);
        } else {
          status_ = value;
        }
      } else {
        statusBuilder_.mergeFrom(value);
      }
      if (status_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>optional .google.rpc.Status status = 2;</code>
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      status_ = null;
      if (statusBuilder_ != null) {
        statusBuilder_.dispose();
        statusBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>optional .google.rpc.Status status = 2;</code>
     */
    public com.google.rpc.Status.Builder getStatusBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetStatusFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>optional .google.rpc.Status status = 2;</code>
     */
    public com.google.rpc.StatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            com.google.rpc.Status.getDefaultInstance() : status_;
      }
    }
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>optional .google.rpc.Status status = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder> 
        internalGetStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:io.pyserve.inference.v1.PredictionResponse)
  }

  // @@protoc_insertion_point(class_scope:io.pyserve.inference.v1.PredictionResponse)
  private static final io.pyserve.inference.v1.PredictionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.pyserve.inference.v1.PredictionResponse();
  }

  public static io.pyserve.inference.v1.PredictionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PredictionResponse>
      PARSER = new com.google.protobuf.AbstractParser<PredictionResponse>() {
    @java.lang.Override
    public PredictionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PredictionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PredictionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.pyserve.inference.v1.PredictionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

