// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inference.proto
// Protobuf Java Version: 4.31.0

package io.pyserve.inference.v1;

/**
 * Protobuf type {@code io.pyserve.inference.v1.PredictionRequest}
 */
@com.google.protobuf.Generated
public final class PredictionRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.pyserve.inference.v1.PredictionRequest)
    PredictionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      PredictionRequest.class.getName());
  }
  // Use PredictionRequest.newBuilder() to construct.
  private PredictionRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PredictionRequest() {
    modelName_ = "";
    modelVersion_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.pyserve.inference.v1.Inference.internal_static_io_pyserve_inference_v1_PredictionRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 3:
        return internalGetInputs();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.pyserve.inference.v1.Inference.internal_static_io_pyserve_inference_v1_PredictionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.pyserve.inference.v1.PredictionRequest.class, io.pyserve.inference.v1.PredictionRequest.Builder.class);
  }

  public static final int MODEL_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object modelName_ = "";
  /**
   * <pre>
   * required
   * </pre>
   *
   * <code>string model_name = 1;</code>
   * @return The modelName.
   */
  @java.lang.Override
  public java.lang.String getModelName() {
    java.lang.Object ref = modelName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * required
   * </pre>
   *
   * <code>string model_name = 1;</code>
   * @return The bytes for modelName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelNameBytes() {
    java.lang.Object ref = modelName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_VERSION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object modelVersion_ = "";
  /**
   * <pre>
   * optional
   * </pre>
   *
   * <code>string model_version = 2;</code>
   * @return The modelVersion.
   */
  @java.lang.Override
  public java.lang.String getModelVersion() {
    java.lang.Object ref = modelVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * optional
   * </pre>
   *
   * <code>string model_version = 2;</code>
   * @return The bytes for modelVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelVersionBytes() {
    java.lang.Object ref = modelVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INPUTS_FIELD_NUMBER = 3;
  private static final class InputsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto>newDefaultInstance(
                io.pyserve.inference.v1.Inference.internal_static_io_pyserve_inference_v1_PredictionRequest_InputsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                io.pyserve.inference.v1.Tensor.TorchTensorProto.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> inputs_;
  private com.google.protobuf.MapField<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto>
  internalGetInputs() {
    if (inputs_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          InputsDefaultEntryHolder.defaultEntry);
    }
    return inputs_;
  }
  public int getInputsCount() {
    return internalGetInputs().getMap().size();
  }
  /**
   * <pre>
   * Input data for model prediction
   * </pre>
   *
   * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; inputs = 3;</code>
   */
  @java.lang.Override
  public boolean containsInputs(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetInputs().getMap().containsKey(key);
  }
  /**
   * Use {@link #getInputsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> getInputs() {
    return getInputsMap();
  }
  /**
   * <pre>
   * Input data for model prediction
   * </pre>
   *
   * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; inputs = 3;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> getInputsMap() {
    return internalGetInputs().getMap();
  }
  /**
   * <pre>
   * Input data for model prediction
   * </pre>
   *
   * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; inputs = 3;</code>
   */
  @java.lang.Override
  public /* nullable */
io.pyserve.inference.v1.Tensor.TorchTensorProto getInputsOrDefault(
      java.lang.String key,
      /* nullable */
io.pyserve.inference.v1.Tensor.TorchTensorProto defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> map =
        internalGetInputs().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Input data for model prediction
   * </pre>
   *
   * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; inputs = 3;</code>
   */
  @java.lang.Override
  public io.pyserve.inference.v1.Tensor.TorchTensorProto getInputsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> map =
        internalGetInputs().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modelName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, modelName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modelVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, modelVersion_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetInputs(),
        InputsDefaultEntryHolder.defaultEntry,
        3);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modelName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, modelName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modelVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, modelVersion_);
    }
    for (java.util.Map.Entry<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> entry
         : internalGetInputs().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto>
      inputs__ = InputsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, inputs__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.pyserve.inference.v1.PredictionRequest)) {
      return super.equals(obj);
    }
    io.pyserve.inference.v1.PredictionRequest other = (io.pyserve.inference.v1.PredictionRequest) obj;

    if (!getModelName()
        .equals(other.getModelName())) return false;
    if (!getModelVersion()
        .equals(other.getModelVersion())) return false;
    if (!internalGetInputs().equals(
        other.internalGetInputs())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MODEL_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getModelName().hashCode();
    hash = (37 * hash) + MODEL_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getModelVersion().hashCode();
    if (!internalGetInputs().getMap().isEmpty()) {
      hash = (37 * hash) + INPUTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetInputs().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.pyserve.inference.v1.PredictionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pyserve.inference.v1.PredictionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pyserve.inference.v1.PredictionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pyserve.inference.v1.PredictionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pyserve.inference.v1.PredictionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.pyserve.inference.v1.PredictionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.pyserve.inference.v1.PredictionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.pyserve.inference.v1.PredictionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.pyserve.inference.v1.PredictionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.pyserve.inference.v1.PredictionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.pyserve.inference.v1.PredictionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.pyserve.inference.v1.PredictionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.pyserve.inference.v1.PredictionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.pyserve.inference.v1.PredictionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.pyserve.inference.v1.PredictionRequest)
      io.pyserve.inference.v1.PredictionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.pyserve.inference.v1.Inference.internal_static_io_pyserve_inference_v1_PredictionRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetInputs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableInputs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.pyserve.inference.v1.Inference.internal_static_io_pyserve_inference_v1_PredictionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.pyserve.inference.v1.PredictionRequest.class, io.pyserve.inference.v1.PredictionRequest.Builder.class);
    }

    // Construct using io.pyserve.inference.v1.PredictionRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      modelName_ = "";
      modelVersion_ = "";
      internalGetMutableInputs().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.pyserve.inference.v1.Inference.internal_static_io_pyserve_inference_v1_PredictionRequest_descriptor;
    }

    @java.lang.Override
    public io.pyserve.inference.v1.PredictionRequest getDefaultInstanceForType() {
      return io.pyserve.inference.v1.PredictionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.pyserve.inference.v1.PredictionRequest build() {
      io.pyserve.inference.v1.PredictionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.pyserve.inference.v1.PredictionRequest buildPartial() {
      io.pyserve.inference.v1.PredictionRequest result = new io.pyserve.inference.v1.PredictionRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.pyserve.inference.v1.PredictionRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.modelName_ = modelName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.modelVersion_ = modelVersion_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.inputs_ = internalGetInputs().build(InputsDefaultEntryHolder.defaultEntry);
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.pyserve.inference.v1.PredictionRequest) {
        return mergeFrom((io.pyserve.inference.v1.PredictionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.pyserve.inference.v1.PredictionRequest other) {
      if (other == io.pyserve.inference.v1.PredictionRequest.getDefaultInstance()) return this;
      if (!other.getModelName().isEmpty()) {
        modelName_ = other.modelName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getModelVersion().isEmpty()) {
        modelVersion_ = other.modelVersion_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      internalGetMutableInputs().mergeFrom(
          other.internalGetInputs());
      bitField0_ |= 0x00000004;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              modelName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              modelVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.google.protobuf.MapEntry<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto>
              inputs__ = input.readMessage(
                  InputsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableInputs().ensureBuilderMap().put(
                  inputs__.getKey(), inputs__.getValue());
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object modelName_ = "";
    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>string model_name = 1;</code>
     * @return The modelName.
     */
    public java.lang.String getModelName() {
      java.lang.Object ref = modelName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>string model_name = 1;</code>
     * @return The bytes for modelName.
     */
    public com.google.protobuf.ByteString
        getModelNameBytes() {
      java.lang.Object ref = modelName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>string model_name = 1;</code>
     * @param value The modelName to set.
     * @return This builder for chaining.
     */
    public Builder setModelName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      modelName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>string model_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearModelName() {
      modelName_ = getDefaultInstance().getModelName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>string model_name = 1;</code>
     * @param value The bytes for modelName to set.
     * @return This builder for chaining.
     */
    public Builder setModelNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      modelName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object modelVersion_ = "";
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>string model_version = 2;</code>
     * @return The modelVersion.
     */
    public java.lang.String getModelVersion() {
      java.lang.Object ref = modelVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>string model_version = 2;</code>
     * @return The bytes for modelVersion.
     */
    public com.google.protobuf.ByteString
        getModelVersionBytes() {
      java.lang.Object ref = modelVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>string model_version = 2;</code>
     * @param value The modelVersion to set.
     * @return This builder for chaining.
     */
    public Builder setModelVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      modelVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>string model_version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearModelVersion() {
      modelVersion_ = getDefaultInstance().getModelVersion();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>string model_version = 2;</code>
     * @param value The bytes for modelVersion to set.
     * @return This builder for chaining.
     */
    public Builder setModelVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      modelVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private static final class InputsConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder, io.pyserve.inference.v1.Tensor.TorchTensorProto> {
      @java.lang.Override
      public io.pyserve.inference.v1.Tensor.TorchTensorProto build(io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder val) {
        if (val instanceof io.pyserve.inference.v1.Tensor.TorchTensorProto) { return (io.pyserve.inference.v1.Tensor.TorchTensorProto) val; }
        return ((io.pyserve.inference.v1.Tensor.TorchTensorProto.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> defaultEntry() {
        return InputsDefaultEntryHolder.defaultEntry;
      }
    };
    private static final InputsConverter inputsConverter = new InputsConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder, io.pyserve.inference.v1.Tensor.TorchTensorProto, io.pyserve.inference.v1.Tensor.TorchTensorProto.Builder> inputs_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder, io.pyserve.inference.v1.Tensor.TorchTensorProto, io.pyserve.inference.v1.Tensor.TorchTensorProto.Builder>
        internalGetInputs() {
      if (inputs_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(inputsConverter);
      }
      return inputs_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder, io.pyserve.inference.v1.Tensor.TorchTensorProto, io.pyserve.inference.v1.Tensor.TorchTensorProto.Builder>
        internalGetMutableInputs() {
      if (inputs_ == null) {
        inputs_ = new com.google.protobuf.MapFieldBuilder<>(inputsConverter);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return inputs_;
    }
    public int getInputsCount() {
      return internalGetInputs().ensureBuilderMap().size();
    }
    /**
     * <pre>
     * Input data for model prediction
     * </pre>
     *
     * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; inputs = 3;</code>
     */
    @java.lang.Override
    public boolean containsInputs(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetInputs().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getInputsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> getInputs() {
      return getInputsMap();
    }
    /**
     * <pre>
     * Input data for model prediction
     * </pre>
     *
     * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; inputs = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> getInputsMap() {
      return internalGetInputs().getImmutableMap();
    }
    /**
     * <pre>
     * Input data for model prediction
     * </pre>
     *
     * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; inputs = 3;</code>
     */
    @java.lang.Override
    public /* nullable */
io.pyserve.inference.v1.Tensor.TorchTensorProto getInputsOrDefault(
        java.lang.String key,
        /* nullable */
io.pyserve.inference.v1.Tensor.TorchTensorProto defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder> map = internalGetMutableInputs().ensureBuilderMap();
      return map.containsKey(key) ? inputsConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <pre>
     * Input data for model prediction
     * </pre>
     *
     * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; inputs = 3;</code>
     */
    @java.lang.Override
    public io.pyserve.inference.v1.Tensor.TorchTensorProto getInputsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder> map = internalGetMutableInputs().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return inputsConverter.build(map.get(key));
    }
    public Builder clearInputs() {
      bitField0_ = (bitField0_ & ~0x00000004);
      internalGetMutableInputs().clear();
      return this;
    }
    /**
     * <pre>
     * Input data for model prediction
     * </pre>
     *
     * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; inputs = 3;</code>
     */
    public Builder removeInputs(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableInputs().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto>
        getMutableInputs() {
      bitField0_ |= 0x00000004;
      return internalGetMutableInputs().ensureMessageMap();
    }
    /**
     * <pre>
     * Input data for model prediction
     * </pre>
     *
     * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; inputs = 3;</code>
     */
    public Builder putInputs(
        java.lang.String key,
        io.pyserve.inference.v1.Tensor.TorchTensorProto value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableInputs().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * Input data for model prediction
     * </pre>
     *
     * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; inputs = 3;</code>
     */
    public Builder putAllInputs(
        java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> values) {
      for (java.util.Map.Entry<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableInputs().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * Input data for model prediction
     * </pre>
     *
     * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; inputs = 3;</code>
     */
    public io.pyserve.inference.v1.Tensor.TorchTensorProto.Builder putInputsBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder> builderMap = internalGetMutableInputs().ensureBuilderMap();
      io.pyserve.inference.v1.Tensor.TorchTensorProtoOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = io.pyserve.inference.v1.Tensor.TorchTensorProto.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof io.pyserve.inference.v1.Tensor.TorchTensorProto) {
        entry = ((io.pyserve.inference.v1.Tensor.TorchTensorProto) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (io.pyserve.inference.v1.Tensor.TorchTensorProto.Builder) entry;
    }

    // @@protoc_insertion_point(builder_scope:io.pyserve.inference.v1.PredictionRequest)
  }

  // @@protoc_insertion_point(class_scope:io.pyserve.inference.v1.PredictionRequest)
  private static final io.pyserve.inference.v1.PredictionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.pyserve.inference.v1.PredictionRequest();
  }

  public static io.pyserve.inference.v1.PredictionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PredictionRequest>
      PARSER = new com.google.protobuf.AbstractParser<PredictionRequest>() {
    @java.lang.Override
    public PredictionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PredictionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PredictionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.pyserve.inference.v1.PredictionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

