// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inference.proto
// Protobuf Java Version: 4.31.0

package io.pyserve.inference.v1;

@com.google.protobuf.Generated
public interface PredictionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.pyserve.inference.v1.PredictionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Output tensors.
   * </pre>
   *
   * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
   */
  int getOutputsCount();
  /**
   * <pre>
   * Output tensors.
   * </pre>
   *
   * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
   */
  boolean containsOutputs(
      java.lang.String key);
  /**
   * Use {@link #getOutputsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto>
  getOutputs();
  /**
   * <pre>
   * Output tensors.
   * </pre>
   *
   * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
   */
  java.util.Map<java.lang.String, io.pyserve.inference.v1.Tensor.TorchTensorProto>
  getOutputsMap();
  /**
   * <pre>
   * Output tensors.
   * </pre>
   *
   * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
   */
  /* nullable */
io.pyserve.inference.v1.Tensor.TorchTensorProto getOutputsOrDefault(
      java.lang.String key,
      /* nullable */
io.pyserve.inference.v1.Tensor.TorchTensorProto defaultValue);
  /**
   * <pre>
   * Output tensors.
   * </pre>
   *
   * <code>map&lt;string, .io.pyserve.inference.v1.TorchTensorProto&gt; outputs = 1;</code>
   */
  io.pyserve.inference.v1.Tensor.TorchTensorProto getOutputsOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * optional
   * </pre>
   *
   * <code>optional .google.rpc.Status status = 2;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <pre>
   * optional
   * </pre>
   *
   * <code>optional .google.rpc.Status status = 2;</code>
   * @return The status.
   */
  com.google.rpc.Status getStatus();
  /**
   * <pre>
   * optional
   * </pre>
   *
   * <code>optional .google.rpc.Status status = 2;</code>
   */
  com.google.rpc.StatusOrBuilder getStatusOrBuilder();
}
